### ISSUE TITLE
关于页面中文字符乱码

### ISSUE THREAD

**Issue by zonglu666** [voidking/subway#2]
您好，我是刚学习Java开发的，我在编译您的项目后，发现页面上的中文是乱码的，我尝试字符全部使用utf-8好像也不可以！
![image](https://cloud.githubusercontent.com/assets/23066347/24917970/5b8b4600-1f11-11e7-95ee-3b4851bb9bc8.png)

**Comment by voidking** [comment]
1、不管你是用的eclipse还是idea，先把IDE的环境设置成utf8。
在eclipse中，Window，Preference，General，Workspace，Text file encoding，Other选择UTF-8。
在idea中，File，settings，Editor，File Encodings，IDE Encoding和Project Encoding设置为UTF-8。
设置好之后，重新编译启动项目。

2、在查看页面时，浏览器页面编码设置为自动或者utf8。

**Comment by kinderry** [comment]
环境设置正确情况下以下这段代码读取编码方式可能为GBK
Template template=config.getTemplate("adminloginpage.ftl"); //加载模板文件  
改为
 Template template=config.getTemplate("adminloginpage.ftl","utf-8");

**Comment by zonglu666** [comment]
![image](https://cloud.githubusercontent.com/assets/23066347/25303843/a9841e66-278d-11e7-895f-2827a9d0e22b.png)
問題已經解決，生成模板的時候，要使用utf-8編碼格式！
